add timeout properties
trocco-io/embulk-input-mysql_binlog pull request #39
Opened 2021-03-23 02:13 UTC by u110

2021-03-23 02:13 UTC, u110 commented on src/main/java/org/embulk/input/mysql_binlog/manager/TableManager.java
> +        props.setProperty("socketTimeout", pluginTask.getSocketTimeoutSec());
他の差分も入ってしまっていますが、
処理として追加したのはこちらです。

2021-03-23 02:15 UTC, u110 commented on src/main/java/org/embulk/input/mysql_binlog/PluginTask.java
> +    String getSocketTimeoutSec();
初期値含めて追加したので、configエラーにはならないが
初期値が小さすぎないか心配。

2021-03-24 06:55 UTC, giwa requested changes
logintimeoutにあたるものがmysqlではみつかりませんでした。

2021-03-24 06:55 UTC, giwa commented on src/main/java/org/embulk/input/mysql_binlog/PluginTask.java
> +    String getSocketTimeoutSec();
https://github.com/embulk/embulk-input-jdbc/tree/master/embulk-input-mysql

embulk のほかの値に合わせるのはどうですか？
socket timeout 1800


https://stackoverflow.com/questions/26250141/jdbc-connecttimeout-vs-jdbc-logintimeout

logintimeout はpsotgresql, JTDSのみサポートされていてmysqlにはないようなんですがどうでしょうか？

2024-05-24 11:54 UTC, closed without merging